### ISSUE TITLE
Entire ViewModel dynamic?

### ISSUE THREAD

**Issue by b9chris** [DalSoft/JsonDotNetValueProviderFactory#1]
It appears the goal of this library is to allow properties of a ViewModel to be dynamic, but is it intended to support for example:

public JsonResult Test(dynamic o) . . .

Where the entire ViewModel is dynamic? Using it in this scenario appears to get an empty object out even though I can step into the ValueProvider and see it properly creating a dynamic object behind the scenes (and then, apparently losing it somewhere down the MVC chain...).

Am I just using it improperly?

**Comment by DalSoft** [comment]
Sorry for the delay in my reply. Currently you can't have a property that is a dynamic for example look at the model below. At the moment the whole model can't be a dynamic. I'm looking at this in a separate project one of the challenges to overcome is over posting.

//Example of a model that won't work with the current JsonValueProviderFactory but will work with JsonDotNetValueProviderFactory
public class CmsViewModel
{
    public bool IsVisible { get; set; }
    public string Content { get; set; }
    public DateTime Modified { get; set; }
    public DateTime Created { get; set; }
    //This property will not work with the current JsonValueProviderFactory
    public dynamic UserDefined { get; set; }
}

**Comment by b9chris** [comment]
Thanks, I've tested and verified this. If you abstract your post calls, like:

function postJson(url, data) {
    return $.ajax({
        data: // pass either data here or { d: data } depending on whether you're using this dynamic approach

Then you can use a simple wrapper InputModel on the backend as a workaround:

[HttpPost]
public JsonResult SaveThing(JsonDynamicWrapper data)
{
    dynamic d = data.d; // Enjoy your fully dynamic InputModel

It appears improving on this where no workaround is necessary would require actually forking MVC itself and modifying the code that prevents this, not my idea of a good time.

**Comment by DalSoft** [comment]
Yes that workaround works too (didn't know that before so thanks), I'm going to get round to giving the MVC team a pull request.  To remove the wrapper you don't need to rewrite MVC though, a model binder that understands this value provider will do the trick. However that's a bit of work too!
